title: Lorenc Bushati
description: CV Lorenc Bushati

baseurl: ""
url: "https://lorenc-bushati.gitlab.io"

show_downloads: false

site.url: "https://lorenc-bushati.gitlab.io"

# Build settings
markdown: kramdown

remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

exclude:
  - .jekyll-cache
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - README.md
  - yarn.lock
